// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: pb/jwtpop.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpireJWTPOPExtension_FetchJWTPOP_FullMethodName = "/SpireJWTPOPExtension/FetchJWTPOP"
)

// SpireJWTPOPExtensionClient is the client API for SpireJWTPOPExtension service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpireJWTPOPExtensionClient interface {
	FetchJWTPOP(ctx context.Context, in *JWTPOPRequest, opts ...grpc.CallOption) (*JWTPOPResponse, error)
}

type spireJWTPOPExtensionClient struct {
	cc grpc.ClientConnInterface
}

func NewSpireJWTPOPExtensionClient(cc grpc.ClientConnInterface) SpireJWTPOPExtensionClient {
	return &spireJWTPOPExtensionClient{cc}
}

func (c *spireJWTPOPExtensionClient) FetchJWTPOP(ctx context.Context, in *JWTPOPRequest, opts ...grpc.CallOption) (*JWTPOPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JWTPOPResponse)
	err := c.cc.Invoke(ctx, SpireJWTPOPExtension_FetchJWTPOP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpireJWTPOPExtensionServer is the server API for SpireJWTPOPExtension service.
// All implementations must embed UnimplementedSpireJWTPOPExtensionServer
// for forward compatibility.
type SpireJWTPOPExtensionServer interface {
	FetchJWTPOP(context.Context, *JWTPOPRequest) (*JWTPOPResponse, error)
	mustEmbedUnimplementedSpireJWTPOPExtensionServer()
}

// UnimplementedSpireJWTPOPExtensionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpireJWTPOPExtensionServer struct{}

func (UnimplementedSpireJWTPOPExtensionServer) FetchJWTPOP(context.Context, *JWTPOPRequest) (*JWTPOPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchJWTPOP not implemented")
}
func (UnimplementedSpireJWTPOPExtensionServer) mustEmbedUnimplementedSpireJWTPOPExtensionServer() {}
func (UnimplementedSpireJWTPOPExtensionServer) testEmbeddedByValue()                              {}

// UnsafeSpireJWTPOPExtensionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpireJWTPOPExtensionServer will
// result in compilation errors.
type UnsafeSpireJWTPOPExtensionServer interface {
	mustEmbedUnimplementedSpireJWTPOPExtensionServer()
}

func RegisterSpireJWTPOPExtensionServer(s grpc.ServiceRegistrar, srv SpireJWTPOPExtensionServer) {
	// If the following call pancis, it indicates UnimplementedSpireJWTPOPExtensionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpireJWTPOPExtension_ServiceDesc, srv)
}

func _SpireJWTPOPExtension_FetchJWTPOP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JWTPOPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpireJWTPOPExtensionServer).FetchJWTPOP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpireJWTPOPExtension_FetchJWTPOP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpireJWTPOPExtensionServer).FetchJWTPOP(ctx, req.(*JWTPOPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpireJWTPOPExtension_ServiceDesc is the grpc.ServiceDesc for SpireJWTPOPExtension service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpireJWTPOPExtension_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SpireJWTPOPExtension",
	HandlerType: (*SpireJWTPOPExtensionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchJWTPOP",
			Handler:    _SpireJWTPOPExtension_FetchJWTPOP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/jwtpop.proto",
}
