// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: pb/jwtpop.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JWTPOPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. Serialised JWK
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Optional. The requested SPIFFE ID for the JWT-SVID. If unset, all
	// JWT-SVIDs to which the workload is entitled are requested.
	SpiffeId string `protobuf:"bytes,2,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// Required. The JWT-SVID audience.
	Audience string `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
}

func (x *JWTPOPRequest) Reset() {
	*x = JWTPOPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_jwtpop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTPOPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTPOPRequest) ProtoMessage() {}

func (x *JWTPOPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_jwtpop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTPOPRequest.ProtoReflect.Descriptor instead.
func (*JWTPOPRequest) Descriptor() ([]byte, []int) {
	return file_pb_jwtpop_proto_rawDescGZIP(), []int{0}
}

func (x *JWTPOPRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *JWTPOPRequest) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *JWTPOPRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

type JWTPOPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpiffeId string        `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	Svids    []*JWTPOPSVID `protobuf:"bytes,2,rep,name=svids,proto3" json:"svids,omitempty"`
}

func (x *JWTPOPResponse) Reset() {
	*x = JWTPOPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_jwtpop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTPOPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTPOPResponse) ProtoMessage() {}

func (x *JWTPOPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_jwtpop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTPOPResponse.ProtoReflect.Descriptor instead.
func (*JWTPOPResponse) Descriptor() ([]byte, []int) {
	return file_pb_jwtpop_proto_rawDescGZIP(), []int{1}
}

func (x *JWTPOPResponse) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *JWTPOPResponse) GetSvids() []*JWTPOPSVID {
	if x != nil {
		return x.Svids
	}
	return nil
}

// The JWTPOPSVID message carries the JWT-SVID token and associated metadata.
type JWTPOPSVID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The SPIFFE ID of the JWT-SVID.
	SpiffeId string `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// Required. Encoded JWT using JWS Compact Serialization.
	Svid string `protobuf:"bytes,2,opt,name=svid,proto3" json:"svid,omitempty"`
	// Optional. An operator-specified string used to provide guidance on how this
	// identity should be used by a workload when more than one SVID is returned.
	// For example, `internal` and `external` to indicate an SVID for internal or
	// external use, respectively.
	Hint string `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *JWTPOPSVID) Reset() {
	*x = JWTPOPSVID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_jwtpop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTPOPSVID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTPOPSVID) ProtoMessage() {}

func (x *JWTPOPSVID) ProtoReflect() protoreflect.Message {
	mi := &file_pb_jwtpop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTPOPSVID.ProtoReflect.Descriptor instead.
func (*JWTPOPSVID) Descriptor() ([]byte, []int) {
	return file_pb_jwtpop_proto_rawDescGZIP(), []int{2}
}

func (x *JWTPOPSVID) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *JWTPOPSVID) GetSvid() string {
	if x != nil {
		return x.Svid
	}
	return ""
}

func (x *JWTPOPSVID) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

var File_pb_jwtpop_proto protoreflect.FileDescriptor

var file_pb_jwtpop_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x6a, 0x77, 0x74, 0x70, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5a, 0x0a, 0x0d, 0x4a, 0x57, 0x54, 0x50, 0x4f, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x50, 0x0a,
	0x0e, 0x4a, 0x57, 0x54, 0x50, 0x4f, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x05,
	0x73, 0x76, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4a, 0x57,
	0x54, 0x50, 0x4f, 0x50, 0x53, 0x56, 0x49, 0x44, 0x52, 0x05, 0x73, 0x76, 0x69, 0x64, 0x73, 0x22,
	0x51, 0x0a, 0x0a, 0x4a, 0x57, 0x54, 0x50, 0x4f, 0x50, 0x53, 0x56, 0x49, 0x44, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x76,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x76, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69,
	0x6e, 0x74, 0x32, 0x46, 0x0a, 0x14, 0x53, 0x70, 0x69, 0x72, 0x65, 0x4a, 0x57, 0x54, 0x50, 0x4f,
	0x50, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x0b, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x4a, 0x57, 0x54, 0x50, 0x4f, 0x50, 0x12, 0x0e, 0x2e, 0x4a, 0x57, 0x54, 0x50,
	0x4f, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x4a, 0x57, 0x54, 0x50,
	0x4f, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x66, 0x69, 0x64, 0x65, 0x2f,
	0x63, 0x6f, 0x66, 0x69, 0x64, 0x65, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x77, 0x69,
	0x6d, 0x73, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_jwtpop_proto_rawDescOnce sync.Once
	file_pb_jwtpop_proto_rawDescData = file_pb_jwtpop_proto_rawDesc
)

func file_pb_jwtpop_proto_rawDescGZIP() []byte {
	file_pb_jwtpop_proto_rawDescOnce.Do(func() {
		file_pb_jwtpop_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_jwtpop_proto_rawDescData)
	})
	return file_pb_jwtpop_proto_rawDescData
}

var file_pb_jwtpop_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_jwtpop_proto_goTypes = []any{
	(*JWTPOPRequest)(nil),  // 0: JWTPOPRequest
	(*JWTPOPResponse)(nil), // 1: JWTPOPResponse
	(*JWTPOPSVID)(nil),     // 2: JWTPOPSVID
}
var file_pb_jwtpop_proto_depIdxs = []int32{
	2, // 0: JWTPOPResponse.svids:type_name -> JWTPOPSVID
	0, // 1: SpireJWTPOPExtension.FetchJWTPOP:input_type -> JWTPOPRequest
	1, // 2: SpireJWTPOPExtension.FetchJWTPOP:output_type -> JWTPOPResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_jwtpop_proto_init() }
func file_pb_jwtpop_proto_init() {
	if File_pb_jwtpop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_jwtpop_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*JWTPOPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_jwtpop_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*JWTPOPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_jwtpop_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*JWTPOPSVID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_jwtpop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_jwtpop_proto_goTypes,
		DependencyIndexes: file_pb_jwtpop_proto_depIdxs,
		MessageInfos:      file_pb_jwtpop_proto_msgTypes,
	}.Build()
	File_pb_jwtpop_proto = out.File
	file_pb_jwtpop_proto_rawDesc = nil
	file_pb_jwtpop_proto_goTypes = nil
	file_pb_jwtpop_proto_depIdxs = nil
}
